net/bridge: Enable bridge also when switchdev can't be built [net-next:build_err]
Currently switchdev doesn't build on older gcc version such as 4.4.6

The reason for the compile error is such that it causes a failure
to build the bridge too, even when switchdev isn't configured (the
stub isn't enough), fix it.

CC [M]  net/bridge/br_stp.o
net/bridge/br_stp.c: In function 'br_set_state':
net/bridge/br_stp.c:44: error: unknown field 'stp_state' specified in initializer

Issue: None
Change-Id: I75d5446aef41cca59a39467801b3d717203212ba
Signed-off-by: Or Gerlitz <ogerlitz@mellanox.com>